name: Build and Upload

on:
  workflow_call:
    inputs:
      isRelease:
        required: true
        type: boolean
      shouldUpload:
        required: true
        type: boolean
    secrets:
      USER:
        required: true
      PASSWORD:
        required: true
      PGP_SECRET:
        required: true
      PGP_PASSPHRASE:
        required: true

env:
  RELEASE: ${{ inputs.isRelease }}

jobs:
  build_Linux:
    name: Build Windows/Linux
    runs-on: ubuntu-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Check Ant
        run: ant -version

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Install NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download imgui source
        run: ./gradlew :gdx-imgui:imgui:generator:download_source

      - name: Build imgui
        run: ./gradlew :gdx-imgui:imgui:generator:build_project
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

#      - name: Test ImGui Core Native
#        run: ./gradlew :imgui:core:core:test

      - name: Upload imgui natives
        uses: actions/upload-artifact@v3
        with:
          name: imgui-natives
          path: ./imgui/generator/build/c++/libs/

#      - name: Upload compiled core natives
#        uses: actions/upload-artifact@v3
#        with:
#          name: coreNativeFiles
#          path: ./imgui/core/core/build/c++/libs/
#
#      - name: Upload extension ImLayout natives
#        uses: actions/upload-artifact@v3
#        with:
#          name: imlayoutNativeFiles
#          path: ./imgui/extensions/imlayout/imlayout-core/build/c++/libs/

  build_Mac:
    name: Build Mac OS
    runs-on: macos-11
    needs: build_Linux

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Install Ant
        run: brew install ant

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Install NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Download imgui natives natives
        uses: actions/download-artifact@v3
        with:
          name: imgui-natives
          path: ./imgui/generator/build/c++/libs/

#      - name: Download compiled core natives
#        uses: actions/download-artifact@v3
#        with:
#          name: coreNativeFiles
#          path: ./imgui/core/core/build/c++/libs/
#
#      - name: Download compiled extension ImLayout
#        uses: actions/download-artifact@v3
#        with:
#          name: imlayoutNativeFiles
#          path: ./imgui/extensions/imlayout/imlayout-core/build/c++/libs/

      - name: Check g++ version
        run: gcc --version

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download imgui source
        run: ./gradlew :gdx-imgui:imgui:generator:download_source

      - name: Build imgui
        run: ./gradlew :gdx-imgui:imgui:generator:build_project
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

#      - name: Test ImGui Core Native
#        run: ./gradlew :imgui:core:core:test

      - name: Upload to repository
        if: ${{ inputs.shouldUpload }}
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SIGNING_KEY: ${{ secrets.PGP_SECRET }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}