name: Build and Upload

on:
  workflow_call:
    inputs:
      isRelease:
        required: true
        type: boolean
      shouldUpload:
        required: true
        type: boolean
    secrets:
      USER:
        required: true
      PASSWORD:
        required: true
      PGP_SECRET:
        required: true
      PGP_PASSPHRASE:
        required: true

env:
  RELEASE: ${{ inputs.isRelease }}

jobs:
  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew download_all_sources

      - name: Build project
        run: ./gradlew :imgui:imgui-build:build_project_windows64

      - name: Build ImLayout library
        run: ./gradlew :extensions:imlayout:imlayout-build:build_project_windows64

      - name: Build ImGuiColorTextEdit library
        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project_windows64

      - name: Build imgui-node-editor library
        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project_windows64

      - name: Build ImGui Extensions
        run: ./gradlew :imgui-ext:ext-build:build_project_windows64

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: windows-natives
          path: ./imgui/imgui-build/build/c++/libs/

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew download_all_sources

      - name: Build project
        run: ./gradlew :imgui:imgui-build:build_project_linux64

      - name: Build ImLayout library
        run: ./gradlew :extensions:imlayout:imlayout-build:build_project_linux64

      - name: Build ImGuiColorTextEdit library
        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project_linux64

      - name: Build imgui-node-editor library
        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project_linux64

      - name: Build ImGui Extensions
        run: ./gradlew :imgui-ext:ext-build:build_project_linux64

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: linux-natives
          path: ./imgui/imgui-build/build/c++/libs/

  build_mac:
    name: Build Mac
    runs-on: macos-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew download_all_sources

      - name: Build project
        run: ./gradlew :imgui:imgui-build:build_project_mac64 :imgui:imgui-build:build_project_macArm

      - name: Build ImLayout library
        run: ./gradlew :extensions:imlayout:imlayout-build:build_project_mac64 :extensions:imlayout:imlayout-build:build_project_macArm

      - name: Build ImGuiColorTextEdit library
        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project_mac64 :extensions:ImGuiColorTextEdit:textedit-build:build_project_macArm

      - name: Build imgui-node-editor library
        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project_mac64 :extensions:imgui-node-editor:nodeeditor-build:build_project_macArm

      - name: Build ImGui Extensions
        run: ./gradlew :imgui-ext:ext-build:build_project_mac64 :imgui-ext:ext-build:build_project_macArm

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: mac-natives
          path: ./imgui/imgui-build/build/c++/libs/

  build_teavm:
    name: Build TeaVM
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew download_all_sources

      - name: Build project
        run: ./gradlew :imgui:imgui-build:build_project_teavm

      - name: Build ImLayout library
        run: ./gradlew :extensions:imlayout:imlayout-build:build_project_teavm

      - name: Build ImGuiColorTextEdit library
        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project_teavm

      - name: Build imgui-node-editor library
        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project_teavm

      - name: Build ImGui Extensions
        run: ./gradlew :imgui-ext:ext-build:build_project_teavm

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: teavm-natives
          path: ./imgui/imgui-build/build/c++/libs/

  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Install NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew download_all_sources

      - name: Build project
        run: ./gradlew :imgui:imgui-build:build_project_android
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: android-natives
          path: ./imgui/imgui-build/build/c++/libs/

#      - name: Install emscripten
#        uses: mymindstorm/setup-emsdk@v14
#
#      - name: Install NDK
#        id: setup-ndk
#        uses: nttld/setup-ndk@v1
#        with:
#          ndk-version: r25c
#          add-to-path: false
#
#      - name: Change wrapper permissions
#        run: chmod +x ./gradlew
#
#      - name: Download ImGui source
#        run: ./gradlew :imgui:imgui-build:download_source
#
#      - name: Build ImGui
#        run: ./gradlew :imgui:imgui-build:build_project
#        env:
#          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#
#      - name: Build ImLayout library
#        run: ./gradlew :extensions:imlayout:imlayout-build:build_project
#        env:
#          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#
#      - name: Download ImGuiColorTextEdit source
#        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:download_source
#
#      - name: Build ImGuiColorTextEdit library
#        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project
#        env:
#          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#
#      - name: Download imgui-node-editor source
#        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:download_source
#
#      - name: Build imgui-node-editor library
#        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project
#        env:
#          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#
#      # With all extensions library set we do the final bind that glue them all
#      - name: Build ImGui Extensions
#        run: ./gradlew :imgui-ext:ext-build:build_project
#        env:
#          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
#
#      - name: Upload imgui natives
#        uses: actions/upload-artifact@v4
#        with:
#          name: imgui-natives
#          path: ./imgui/imgui-build/build/c++/libs/
#
#  build_Mac:
#    name: Build Mac OS
#    runs-on: macos-13
#    needs: build_Linux
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v4
#        with:
#          distribution: "zulu"
#          java-version: 11
#
#      - name: Download imgui natives natives
#        uses: actions/download-artifact@v4
#        with:
#          name: imgui-natives
#          path: ./imgui/imgui-build/build/c++/libs/
#
#      - name: Change wrapper permissions
#        run: chmod +x ./gradlew
#
#      - name: Download ImGui source
#        run: ./gradlew :imgui:imgui-build:download_source
#
#      - name: Build ImGui
#        run: ./gradlew :imgui:imgui-build:build_project
#
#      - name: Build ImLayout library
#        run: ./gradlew :extensions:imlayout:imlayout-build:build_project
#
#      - name: Download ImGuiColorTextEdit source
#        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:download_source
#
#      - name: Build ImGuiColorTextEdit library
#        run: ./gradlew :extensions:ImGuiColorTextEdit:textedit-build:build_project
#
#      - name: Download imgui-node-editor source
#        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:download_source
#
#      - name: Build imgui-node-editor library
#        run: ./gradlew :extensions:imgui-node-editor:nodeeditor-build:build_project
#
#      # With all extensions library set we do the final bind that glue them all
#      - name: Build ImGui Extensions
#        run: ./gradlew :imgui-ext:ext-build:build_project
#
#      - name: Upload to repository
#        if: ${{ inputs.shouldUpload }}
#        run: ./gradlew publish
#        env:
#          USER: ${{ secrets.USER }}
#          PASSWORD: ${{ secrets.PASSWORD }}
#          SIGNING_KEY: ${{ secrets.PGP_SECRET }}
#          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}