name: Deploy Libs

on:
  push:
    branches:
      - master

jobs:
  build_Linux:
    name: Build Windows/Linux
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Ant
        run: ant -version
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Fetch imgui and build native files
        run: ./gradlew :buildImGuiNatives
      - name: Upload compiled imgui-core natives
        uses: actions/upload-artifact@v1
        with:
          name: coreNativeFiles
          path: ./imgui/imgui-core/imgui-core/libs/
#      - name: Upload compiled imgui-ext natives
#        uses: actions/upload-artifact@v1
#        with:
#          name: imlayoutNativeFiles
#          path: ./extensions/imgui-ext/libs/

  build_Mac:
    name: Build Mac OS
    runs-on: macos-latest
    needs: build_Linux

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Ant
        run: brew install ant
      - name: Download compiled natives
        uses: actions/download-artifact@v1
        with:
          name: coreNativeFiles
          path: ./imgui/imgui-core/imgui-core/libs/
#      - name: Download compiled ext natives
#        uses: actions/download-artifact@v1
#        with:
#          name: imlayoutNativeFiles
#          path: ./extensions/imgui-ext/libs/
      - name: Check g++ version
        run: gcc --version
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Fetch imgui and build native files
        run: ./gradlew :buildImGuiNatives
      - name: Upload to repository
        run: ./gradlew publish
        env:
          IMGUI_USER: ${{ secrets.IMGUI_USER }}
          IMGUI_PASSWORD: ${{ secrets.IMGUI_PASSWORD }}